### ISSUE TITLE
Error while running event bbpp::bbpp:confirm-gui-linked (ID 178)

### ISSUE THREAD

**Issue by safron7979** [GlassBricks/bbpp#1]
Error while running event bbpp::bbpp:confirm-gui-linked (ID 178)
LuaEquipment doesn't contain key tags.
stack traceback:
	[C]: in function '__index'
	__bbpp__/framework/gui/confirm.lua:17: in function 'handler'
	__bbpp__/framework/events.lua:15: in function <__bbpp__/framework/events.lua:13>
24510.652 Info AppManager.cpp:1389: Restarting Factorio
24510.771 Quitting: user-quit.

**Comment by GlassBricks** [comment]
Should be fixed in v0.1.1.
